version: '3.8'

services:
  frontend:
    container_name: next_app
    restart: always
    build:
      context: ./
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    network_mode: 'bridge'